const API_PUBLIC_URI = process.env.NEXT_PUBLIC_API_PUBLIC_URI;
const API_CHATBOT_PUBLIC_URI = process.env.NEXT_PUBLIC_API_CHATBOT_PUBLIC_URI
const STRIPE_SECRET_KEY = process.env.NEXT_PUBLIC_STRIPE_SECRET_KEY;

export { API_PUBLIC_URI, STRIPE_SECRET_KEY, API_CHATBOT_PUBLIC_URI };
