const API_PUBLIC_URI = process.env.NEXT_PUBLIC_API_PUBLIC_URI;
const API_CHATBOT_PUBLIC_URI = process.env.NEXT_PUBLIC_API_CHATBOT_PUBLIC_URI;
const STRIPE_SECRET_KEY = process.env.NEXT_PUBLIC_STRIPE_SECRET_KEY;
const STRIPE = process.env.NEXT_PUBLIC_STRIPE;
const AUTH_SECRET = process.env.NEXT_PUBLIC_AUTH_SECRET;
const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
const FIREBASE_AUTH_DOMAIN = process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
const FIREBASE_PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
const FIREBASE_STORAGE_BUCKET = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
const FIREBASE_MESSAGING_SENDER_ID = process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
const FIREBASE_APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APP_ID;
const CLOUDINARY_CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_CLOUD_API_KEY = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_API_KEY;
const CLOUDINARY_CLOUD_API_SECRET = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_API_SECRET;
const IMAGE_HOSTING_API = process.env.NEXT_PUBLIC_IMAGE_HOSTING_API;
const IMAGE_HOSTING_KEY = process.env.NEXT_PUBLIC_IMAGE_HOSTING_KEY;

export {
  API_PUBLIC_URI,
  STRIPE_SECRET_KEY,
  API_CHATBOT_PUBLIC_URI,
  STRIPE,
  AUTH_SECRET,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  CLOUDINARY_CLOUD_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_CLOUD_API_SECRET,
  IMAGE_HOSTING_API,
  IMAGE_HOSTING_KEY
};
