import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { ContextProvider } from '../contexts/ContextProvider';
import { QueryProvider } from '@/query/QueryProvider';
//import css
import '@/components/atoms/ButtonCommon/button.css';
import '@/components/atoms/Input/index.css';
import '@/app/(auth)/sign-in/sign-in.css';
import '@/app/(auth)/sign-up/sign-up.css';
import '@/components/molecules/Pagination/pagination.css';
import '@/components/atoms/Selection/selection.css';
import StoreProvider from './StoreProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
});

export const metadata: Metadata = {
  title: 'Room Manager System',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <QueryProvider>
            <ContextProvider>
              <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
                {children}
              </ThemeProvider>
            </ContextProvider>
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
